### ISSUE TITLE
Dataproc cluster jupyter notebook problem (Creating Notebook Failed)

### ISSUE THREAD

**Issue by paulgeek06** [GoogleCloudPlatform/dataproc-initialization-actions#292] opened 2018-07-10 08:57 UTC
Hello, 
I have followed this tutorial to install a dataproc cluster (spark) with jupyter notebook above. And added in the initialization actions setting those : 
- gs://dataproc-initialization-actions/datalab/datalab.sh
- gs://dataproc-initialization-actions/jupyter/jupyter.sh

Then, the ports I have chosen following this command in cloud shell console : 
- gcloud compute ssh master-host-name --project=project-id --zone master-host-zone -- -4 -N -L port1:master-host-name:port2
is 8080 for port1 and 8123 for port2. 
It worked correctly, But when I open jupyter notebook in a browser, and try to create a new notebook (pyspark or python 3), I get a pop up telling me "Creating Notebook Failed", "An error occurred while creating a new notebook.", "error".

I have tried to figure this out, but I struggled a lot. Could you please helping me ? 

Thank you a lot in advance

**Comment by karth295** [comment] 2018-07-20 03:18
Closing as a duplicate of #290

**Closed by karth295** 2018-07-20 03:18 UTC
