### ISSUE TITLE
gcloud dataproc cluster create with cloud-sql-proxy dataproc-initialization-actions fails

### ISSUE THREAD

**Issue by v-sharma** [GoogleCloudPlatform/dataproc-initialization-actions#294] opened 2018-07-19 19:25 UTC
Steps to reproduce:
1. Create GCP project. 
2. Spin up a Cloud SQL instance (Type: MySQL 2nd Gen 5.7).
3. Create a dataproc cluster with initialization action to install cloud sql proxy and configure the cluster to store Apache Hive metadata on Cloud SQL instance created in step 2.
Command used:
gcloud dataproc --region <REGION - same as Cloud SQL instance> \
clusters create <CLUSTER NAME> \
--subnet default --zone <ZONE same as Cloud SQL instance> \
--scopes sql-admin \
--initialization-actions gs://dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh \
--properties hive:hive.metastore.warehouse.dir=gs://<HIVE_BUCKET>/hive-warehouse \
--metadata "hive-metastore-instance=<PROJECT-ID>:<REGION>:< INSTANCE_NAME>" \
--master-machine-type n1-standard-1 --master-boot-disk-size 10 \
--num-workers 2 \
--worker-machine-type n1-standard-1 --worker-boot-disk-size 10 \
--image-version 1.2 \
--project <PROJECT NAME>

The cluster is created but Initialization action failed. Failed action 'gs://dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh'.

Logs are attached.

[google-cloud-dataproc-metainfo-dataproc-startup-script_output.txt](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/files/2211377/google-cloud-dataproc-metainfo-dataproc-startup-script_output.txt)
[google-cloud-dataproc-metainfo-dataproc-initialization-script-0_output.txt](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/files/2211380/google-cloud-dataproc-metainfo-dataproc-initialization-script-0_output.txt)

**Comment by samschlegel** [comment] 2018-07-20 19:40
Did you set a password when creating the instance? If so, you need to pass in an admin password in order for the script to setup the hive user and other tables. I'd suggest setting up these passwords with KMS, which is detailed in the README

**Comment by Git4Vishal** [comment] 2018-07-20 20:13
Cloud SQL instance was created without admin password set.

**Comment by Git4Vishal** [comment] 2018-07-27 21:37
@karth295 - we are not using any non-default firewall rules. All the spellings project, region and instance names are correct. If not for those then would have encountered a different error. 

About the "set -x" - where should this change be made?

**Comment by karth295** [comment] 2018-07-28 01:11
You can change the line that says `set -euo pipefail` to `set -euxo pipefail`. The `-x` flag means print every command before running it. Then, upload your copy of `cloud-sql-proxy.sh` to a GCS bucket and use `--initialization-actions gs://<your-bucket>/cloud-sql-proxy.sh`.

**Comment by sanjay-94** [comment] 2018-07-30 07:40
I am also facing the same issue. I have added the -x option and here are my logs. 

`++ /usr/share/google/get_metadata_value attributes/metastore-proxy-port
++ echo 3306
+ metastore_proxy_port=3306
+ [[ true != \t\r\u\e ]]
+ local proxy_instances_flags
+ proxy_instances_flags=
+ configure_proxy_flags
+ [[ true = \t\r\u\e ]]
+ [[ -z digital2go-1186:us-central1:d2go-metastore ]]
+ [[ digital2go-1186:us-central1:d2go-metastore =~ .+:.+:.+ ]]
+ [[ digital2go-1186:us-central1:d2go-metastore =~ =tcp:[0-9]+$ ]]
+ metastore_instance+==tcp:3306
+ proxy_instances_flags+=' -instances=digital2go-1186:us-central1:d2go-metastore=tcp:3306'
+ [[ -n '' ]]
+ [[ Master == \M\a\s\t\e\r ]]
+ [[ true = \t\r\u\e ]]
+ systemctl is-enabled --quiet hive-metastore
hive-metastore.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install is-enabled hive-metastore
+ systemctl stop hive-metastore
+ systemctl is-enabled --quiet mysql
mysql.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install is-enabled mysql
+ systemctl stop mysql
+ systemctl disable mysql
mysql.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable mysql
insserv: warning: current start runlevel(s) (empty) of script `mysql' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `mysql' overrides LSB defaults (0 1 6).
+ install_cloud_sql_proxy
+ wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
+ mv cloud_sql_proxy.linux.amd64 /usr/local/bin/cloud_sql_proxy
+ chmod +x /usr/local/bin/cloud_sql_proxy
+ mkdir -p /var/run/cloud_sql_proxy
+ cat
+ chmod a+rw /usr/lib/systemd/system/cloud-sql-proxy.service
+ systemctl enable cloud-sql-proxy
Created symlink /etc/systemd/system/multi-user.target.wants/cloud-sql-proxy.service �~F~R /usr/lib/systemd/system/cloud-sql-proxy.service.
+ systemctl start cloud-sql-proxy
+ echo 'Cloud SQL Proxy installation succeeded'
Cloud SQL Proxy installation succeeded
+ [[ true = \t\r\u\e ]]
+ cat
+ bdconfig merge_configurations --configuration_file /etc/hive/conf/hive-site.xml --source_configuration_file hive-template.xml --clobber
+ [[ true = \t\r\u\e ]]
+ [[ mysql-test-m == \m\y\s\q\l\-\t\e\s\t\-\m ]]
+ configure_sql_client
+ cat
+ mysql -u hive -phive-password -e ''
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
+ mysql -u root '' -e 'CREATE USER '\''hive'\'' IDENTIFIED BY '\''hive-password'\'';'
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

**Comment by sanjay-94** [comment] 2018-07-30 08:18
Even I am facing the same issue. Adding the -x option to pipefail showed me that the initialisation action was failing in configure_sql_client function, to be precise here...
`# Check if metastore is initialized.
  if ! mysql -u "${db_hive_user}" "${db_hive_password_parameter}" -e ''; then`. 
It shows the following error:
`Lost connection to MySQL server at 'reading initial communication packet', system error: 0`
I tried manually running the above query by passing the -h <host_ip> and it connects for the root user and not the hive user.

**Comment by sanjay-94** [comment] 2018-07-31 00:50
The initialisation script works with older dataproc images 1.2.0, but not with the latest ones

**Comment by cocoza4** [comment] 2018-09-27 08:58
Any update on this. I had a pretty similar problem but in my case it says

+ mysql -u hive -phive-password -e ''
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)
+ mysql -u root '' -e 'CREATE USER '\''hive'\'' IDENTIFIED BY '\''hive-password'\'';'
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)

However when I ssh to the cluster's master node and execute "mysql -u hive -phive-password" I'm able to connect to MySQL.

thanks

**Comment by martynbristow** [comment] 2018-09-27 09:41
@cocoza4 We are seeing this issue to, it appears to be the script is failing to start the proxy before using the connection. I think we've strayed onto a separate issue so that should be raised separately

**Comment by martynbristow** [comment] 2018-09-27 10:01
Not yet .. I'm currently in the process of reproducing

**Comment by cocoza4** [comment] 2018-09-27 10:18
@martynbristow seems like someone has done it for us. see
https://stackoverflow.com/questions/52532496/dataproc-hive-error-2003-hy000-cant-connect-to-mysql-server-on-localhost

**Comment by karth295** [comment] 2018-09-27 18:14
Looks like @dennishuo authored a fix in #356 based on the error on the stackoverflow post. Is that the same error as in OP's case though? @v-sharma do you mind trying Dennis's fix?

**Comment by dennishuo** [comment] 2018-09-27 22:39
FYI we also narrowed down the change to an upstream release of cloud-sql-proxy updating the binary under dl.google.com earlier this week, (Sept 24, 7:30 PM pacific time); if the failures started around that time, then it's highly likely the same root cause, and picking up https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/356 should fix it for you.

**Comment by karth295** [comment] 2019-06-14 06:58
I'm going to close this issue because it is a year old, and multiple fixes have gone into this init action: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commits/master/cloud-sql-proxy, including adding integration tests.

**Closed by karth295** 2019-06-14 06:58 UTC
